public class Arthimaticcalculations{
    public void Addition (integer x, integer y){
        integer Z=x+y;
        system.debug(z);
        }
        
        public void Subtraction(integer x , integer y){
        integer Z=x-y;
        system.debug(z);}

        public void Multiplication(Integer x, integer y, Integer m){
            integer z=x*y*m;
            system.debug(z);

        }
      
        }
