public class checkDatatypes {
    public void methodBoolean(){
        Boolean checkBoolean = true;
        system.debug(checkBoolean);
    }

    public void methodInteger(){
        integer varfirst = 1;
        integer varsecond = 2;

        system.debug(varfirst);
        system.debug(varsecond);
    }

    public void stringmethod(){
        String varName= 'Name';
        string var2Name = 'Your Name';

        system.debug(varName);
        system.debug(var2Name);
    }

}
