public  class PrimitiveDataTypeDemo {
 public void print1() {

    Id id1 = '0018Z00002f06cnQAA';
    system.debug('print id=' + id1);


    Object obj1= 'This is a string';
    Object obj2= 15;
    Object obj3= '0018Z00002f06cnQAA';
    Object obj4= true;
    
    system.debug('obj1 = ' +obj1);
    system.debug('obj2 = ' +obj2);
    system.debug('obj3 = ' +obj3);
    system.debug('obj4 = ' +obj4);

    }

 

}
