public  class Primitivedata_Assignment {
    public void print1() {
        Id id1 = '0018Z00002f06cnQAA';
        system.debug('print id=' + id1 );

        Object obj1= 'the following id belongs to Accounts.';
        system.debug('obj1 = ' +obj1);

        
        Object obj2= true;
        system.debug('obj2 = ' +obj2);
         
    system.debug('This is ' +obj1 + ' This is the ID '+ id1 +' and that is '+obj2 );
        

    }
}
